title: Using a Piezoelectric Buzzer with a Raspberry Pi
hero_image: images/banner.png
subtitle: rpi-python-piezoelectric-buzzer subtitle
description: rpi-python-piezoelectric-buzzer description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
published: false
steps:
  - title: Controlling a buzzer

