title: Using a Buzzer with a Raspberry Pi
hero_image: images/banner.png
description: Use a buzzer with your Raspberry Pi
original_url:
theme: cc-prototype
listed: false
duration: 1
ingredient: true
copyedit: false
interests:
technologies: "physical computing, rpi, python"
steps:
  - title: Controlling a buzzer

